language: python
python:
- '3.5'
install: pip install -r req.txt
services:
- docker
before_install:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
script:
- python3 conftest.py
- docker build --no-cache -t amritanshu16/hivery-challenge .
- docker tag amritanshu16/hivery-challenge:latest amritanshu16/hivery-challenge:v1
- docker push amritanshu16/hivery-challenge
