language: python
python:
  - "3.5"
install: "pip install -r req.txt"
services:  
  #Enable docker service inside travis
  - docker

before_install:  
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:  
  - python3 conftest.py
  #build the image
  - docker build --no-cache -t amritanshu16/hivery-challenge .
  #tag the build
  - docker tag amritanshu16/hivery-challenge:latest amritanshu16/hivery-challenge:v1
  #push the image to the repository
  - docker push amritanshu16/hivery-challenge